votingworks/bsd

- src/App.tsx
- src/hooks/useInterval.ts
I think you're gonna like this one.
> Use hook for intervals.

- src/screens/DashboardScreen.tsx
we'll bring it back when the features is working.
> removed invalidate button for now.

- src/App.css
- src/components/Table.tsx
- src/screens/DashboardScreen.tsx
Component was created to be shared with `ems`
> Create table component for use in other apps.

- README.md
- src/App.tsx
- src/components/Prose.tsx
- src/screens/DashboardScreen.tsx
Fixes #43
Ideally we update QR Code scanning to be handled with a solution other than using a text input (such as a window listener), but until then, this is a fine solution.
> Scrolling Issue Fix

- .eslintignore
- .eslintrc.js
- .stylelintrc.js
- package.json
- src/App.tsx
- src/components/Button.tsx
- src/components/Text.tsx
- src/hooks/useInterval.ts
- src/screens/DashboardScreen.tsx
- src/screens/LoadElectionScreen.tsx
- src/serviceWorker.ts
- tsconfig.json
- yarn.lock
@beausmith, this updates stylelint which wanted me to alphabetize CSS properties. Let me know if this is not how you'd like it.
> build(deps): upgrade dependencies

- package.json
These thresholds are the rounded-down current coverage values.
> test(coverage): set minimum coverage thresholds

- package.json
- src/hooks/useStateWithLocalStorage.test.tsx
- yarn.lock
Required `@testing-library/react`, which required an update to `react`.
> test(coverage): add tests for `useStateWithLocalStorage`

- .eslintignore
- package.json
- src/util/ballot-package.test.ts
- test/util/zip.ts
- tsconfig.json
- types/compress-commons.d.ts
- types/zip-stream.d.ts
- yarn.lock
Tests a few non-happy path cases.
> test(coverage): improve `ballot-package` util coverage

- .eslintrc.js
- package.json
- src/App.test.tsx
- src/App.tsx
- src/api/config.test.ts
- src/config/types.ts
- src/screens/BallotScreen.test.tsx
- src/screens/BallotScreen.tsx
- src/screens/BatchScreen.test.tsx
- src/screens/BatchScreen.tsx
- src/screens/DashboardScreen.test.tsx
- src/screens/DashboardScreen.tsx
- src/setupTests.ts
- src/util/fetchJSON.test.ts
- yarn.lock
This allows us to view the associated scanned images, with basic highlighting of the marks on the page.
Depends on https://github.com/votingworks/module-scan/pull/79
> feat: allow browsing ballots in a batch

- .eslintrc.js
- package.json
- src/config/types.ts
- src/config/types/ballot-review.ts
- src/screens/BallotScreen.test.tsx
- src/screens/BallotScreen.tsx
- src/screens/BatchScreen.tsx
- src/workflows/BallotScreenWorkflow.test.ts
- src/workflows/BallotScreenWorkflow.ts
Depends on https://github.com/votingworks/module-scan/pull/81.
> feat: basic HMPB adjudication

- src/App.test.tsx
- src/App.tsx
Without this, being on a batch or ballot URL makes reloading the page fail.
> fix: go to main screen on zero/reset/etc

- src/config/types/ballot-review.ts
- src/screens/BallotScreen.tsx
- src/workflows/BallotScreenWorkflow.test.ts
- src/workflows/BallotScreenWorkflow.ts
Updates bsd to be compatible with https://github.com/votingworks/module-scan/pull/90.
> refactor: clarify mark status values

- package.json
- src/App.tsx
- src/components/USBController.test.tsx
- src/components/USBController.tsx
- src/lib/usbstick.test.ts
- src/lib/usbstick.ts
- src/setupProxy.js
- test/helpers/fakeKiosk.ts
- types/kiosk-browser.d.ts
- yarn.lock
Addresses https://github.com/votingworks/vxmail/issues/108
> move USB stick control to kiosk

- src/App.tsx
- types/kiosk-browser.d.ts
Resolves https://github.com/votingworks/vxmail/issues/68
> use kiosk for downloading CVR file

- src/App.test.tsx
- src/App.tsx
- src/components/Button.tsx
- src/components/ButtonBar.tsx
- src/components/LinkButton.tsx
- src/components/USBController.tsx
- src/config/types.ts
- src/config/types/ballot-review.ts
- src/screens/BallotReviewScreen.test.tsx
- src/screens/BallotReviewScreen.tsx
- src/screens/DashboardScreen.test.tsx
- src/screens/DashboardScreen.tsx
- src/workflows/BallotReviewScreenWorkflow.test.ts
- src/workflows/BallotReviewScreenWorkflow.ts
Depends on votingworks/module-scan#102. I didn't have time to finish getting the tests & coverage up to snuff, so someone else will have to do that.
> feat: allow adjudicating bad scans with metadata

- src/App.tsx
- src/workflows/BallotReviewScreenWorkflow.ts
My VM was (is?) running out of memory. I think this may be the cause. 
Regardless, this dramatically increases app performance.
> bug: Only render when data changes.

- src/config/types.ts
- src/screens/DashboardScreen.test.tsx
- src/screens/DashboardScreen.tsx
Depends on https://github.com/votingworks/module-scan/pull/131
> fix: show timestamps correctly for ISO timestamps

- README.md
- public/index.html
- src/components/Brand.tsx
- src/components/ButtonBar.tsx
- src/components/MainNav.tsx
- src/screens/__snapshots__/BallotEjectScreen.test.tsx.snap
> Update app name to "Ballot Scanner" and brand the navigation

- src/AppRoot.tsx
Refs votingworks/module-scan#151
Refs votingworks/vxmail#230
> fix: show feedback for test/live mode switching

- src/AppRoot.tsx
- src/screens/AdvancedOptionsScreen.test.tsx
- src/screens/AdvancedOptionsScreen.tsx
- src/util/download.test.ts
- src/util/download.ts
- types/kiosk-browser.d.ts
> feat: add backup button to download a backup

- prodserver/index.js
also sneaking in some cache-control directives we forgot on this one.
> support reload: fall back to React

- package.json
- src/App.test.tsx
- src/AppRoot.tsx
- src/components/MainNav.tsx
- src/components/USBController.tsx
- src/config/globals.ts
- src/screens/AdvancedOptionsScreen.test.tsx
- src/screens/AdvancedOptionsScreen.tsx
- src/screens/__snapshots__/BallotEjectScreen.test.tsx.snap
- src/util/IntlDateTimeFormats.ts
> Add election data to ui and move test toggle to advanced page

- src/AppRoot.tsx
resolves https://github.com/votingworks/vxmail/issues/233
Merge if LGTY.
> fix: Enable scan button if module-scan is not available.

- src/AppRoot.tsx
- src/components/USBController.test.tsx
- src/components/USBControllerButton.tsx
Related: https://github.com/votingworks/vxmail/issues/110
> fix: USBControllerButton always returns a button.

- src/AppRoot.tsx
- src/components/MainNav.tsx
- src/components/StatusFooter.tsx
- src/components/Text.tsx
- src/screens/__snapshots__/BallotEjectScreen.test.tsx.snap
> feat: Alternate design for election info.

- package.json
- src/config/types.ts
- src/screens/BallotEjectScreen.test.tsx
- yarn.lock
Also upgrade ballot-encoder, cause needed and wow was it old.
> update data structure for adjudication sheets.

- src/screens/BallotEjectScreen.test.tsx
- src/screens/BallotEjectScreen.tsx
- src/screens/__snapshots__/BallotEjectScreen.test.tsx.snap
> Eject with adudication reasons

- package.json
- src/components/ContestOptionButton.tsx
- src/config/types.ts
- src/config/types/ballot-review.ts
- src/screens/BallotEjectScreen.test.tsx
- src/screens/BallotEjectScreen.tsx
- src/screens/BallotReviewScreen.test.tsx
- src/screens/__snapshots__/BallotEjectScreen.test.tsx.snap
- src/util/ballot-package.ts
- src/util/relativeRect.ts
- src/workflows/BallotReviewScreenWorkflow.test.ts
- yarn.lock
This shows only a basic version of what we'd like it to be, wiring up the changes from the backend.
> feat: show ballot sheet adjudication reasons

- src/App.test.tsx
- src/AppRoot.tsx
- src/api/hmpb.ts
- src/screens/LoadElectionScreen.tsx
inform backend when done loading templates, and show error if interpreter not ready.
> prevent startup issues

- src/screens/BallotEjectScreen.tsx
- src/screens/__snapshots__/BallotEjectScreen.test.tsx.snap
It was buried before, now it's in your face and you can't miss it.
> make ballot rejection reason super obvious
